version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  lint-dockerfile:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Hadolint
          command: |
            curl -Lo /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t ghcr.io/assidiqi598/karsajobs-ui:latest .
      - run:
          name: Push Docker image to GHCR
          command: |
            echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "assidiqi598" --password-stdin
            docker push ghcr.io/assidiqi598/karsajobs-ui:latest

workflows:
  version: 2
  karsajobs-ui-pipeline:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only: karsajobs-ui
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
          filters:
            branches:
              only: karsajobs-ui
